[package]
name = "paraphrase"
version = "0.1.0"
authors = ["Jason Hansel <jason@jasonhansel.com>"]

[dependencies]
serde_json = "1.0"
futures = "0.1"
futures-cpupool = "0.1"
rand = "0.4"
regex = "0.2"
structopt="0.1"
structopt-derive="0.1"
